Pagination
GridProtectionAlliance/openXDA pull request #218
Opened 2024-01-25 17:20 UTC by prestoncraw

Added Pagination to the AlarmGroupView Table in `SPCTools` AlarmGroup component to fix issue with controller. I also cleaned up the row and col divs in the `AlarmGroup` component to fix issue with overflow css properties triggering when they shouldn't.

2024-01-27 15:26 UTC, clackner-gpa commented
@prestoncraw Can you wait until #217 is merged then rebase and change `isPivot` in the SearchFilter` to `IsPivot`? otherwhise searches won't work

2024-01-29 15:06 UTC, prestoncraw commented
> @prestoncraw Can you wait until #217 is merged then rebase and change `isPivot` in the SearchFilter`to`IsPivot`? otherwhise searches won't work

Will do

2024-02-01 15:02 UTC, clackner-gpa requested changes

2024-02-01 15:40 UTC, clackner-gpa approved these changes

2024-02-01 15:40 UTC, merged