Added DOCKERFIle
GridProtectionAlliance/openXDA pull request #338
Opened 2024-08-16 23:49 UTC by clackner-gpa

Updated Installer and added DOCKER file

2024-08-28 19:17 UTC, StephenCWills requested changes

2024-08-28 19:17 UTC, StephenCWills commented on Source/Dependencies/GSF/GSF.Web.dll.config
Do we need this file? I feel like it shouldn't even exist upstream.

2024-08-28 19:17 UTC, StephenCWills commented on Source/Applications/openXDA/openXDA/wwwroot/SPCTools/Scripts/js/SPCTools.js
This gets generated when compiling TypeScript. We shouldn't be adding it to the repo, right? Maybe we need a `.gitignore` entry to avoid this.

2024-08-28 19:17 UTC, StephenCWills commented on Source/Applications/openXDA/openXDASetup/openXDASetup.wxs
> +    <SetProperty Action="SetDataBase" Id="DATABASENAME" Value="[SERVICENAME]" After="LaunchConditions" Sequence="first"><![CDATA[NOT DATABASENAME]]></SetProperty>
```suggestion
    <SetProperty Action="SetDatabase" Id="DATABASENAME" Value="[SERVICENAME]" After="LaunchConditions" Sequence="first"><![CDATA[NOT DATABASENAME]]></SetProperty>
```

2024-08-28 19:17 UTC, StephenCWills commented on Source/Applications/openXDA/openXDASetup/openXDASetup.wxs
> +
```suggestion
```

2024-09-06 13:45 UTC, clackner-gpa commented on Source/Dependencies/GSF/GSF.Web.dll.config
I have no idea. If you think we can delete it let's go ahead and remove it.

2024-09-06 18:23 UTC, StephenCWills commented on Source/Applications/openXDA/openXDA/wwwroot/SPCTools/Scripts/js/SPCTools.js
It does appear to have a prebuild event for SPC Tools.

https://github.com/GridProtectionAlliance/openXDA/blob/f2da1e7df32b47876022a321419b520971dd76ac/Source/Applications/openXDA/openXDA/openXDA.csproj#L4586-L4590

2024-09-16 17:44 UTC, StephenCWills approved these changes

2024-09-16 17:56 UTC, merged