Added data operation failure table and a partially succesful status X…
GridProtectionAlliance/openXDA pull request #388
Opened 2024-11-18 20:14 UTC by gcsantos-gpa

…DA-49

2025-01-07 11:30 UTC, clackner-gpa requested changes

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +            FileGroupProcessingStatus processingStatus = FileGroupProcessingStatus.Failed;
Previously if `(meterDataSet is null)`  it would got into `FileGroupProcessingStatus.Processed` state while now it will remain in `Failed` that seems to be an issue. Technically I am not sure who frequent that is since it should not reach the `AnalysisNode` in most cases but I think there is a potential for issues here.

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    if (IsDisposed)
I am pretty sure this will generate multiple failures now. Previously `IsDisposed` caused it to exit the `Process` function completly. Now it will move on to the next `dataOperationDefinition `. Because `IsDisposed` is global for all `dataOperationDefinigitons` we end up with the same error message multiple times. at the very least we should prevent that

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    else if (status == FileGroupProcessingStatus.Failed) status = FileGroupProcessingStatus.PartialSuccess;
This logic seems off. 
If it has 3 `dataOperationDefinitions` (and all suceed) it will go:
from `Failure` to `Success` in `index = 0` 
not change in `index = 1` and `index = 2`

But if the last one fails it will go 
from `Failure` to `Success` in `index = 0` 
not change in `index = 1` and 
from `Success` to `Failure` in `index = 2` which is not correct.

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    if (IsDisposed)
If we dispose we need to consider the entire Processing `Failed`.
`PartialSuccess` should only apply to failures inside 
```
 meterDataSet.Configure(dataOperation);
 dataOperation.Execute(meterDataSet);
 ```
 If the underlying infrastiurcture `AnalysisNode` fails that is considered a complete failure since It will not even attepmt to run the rest of the analytics

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> -            FileGroup fileGroup = meterDataSet.FileGroup;
removing that seems problematic - though it could be a result of Github not aligning changes well. Is that still in there somewhere

2025-01-07 11:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
>          }
We need to make sure if that table is missing it does not take everything down with it.
Probably should tunr this into `TryLogDataOperationFailures` and wrap everything in a `try/catch` with a standard log if it fails.

2025-01-10 14:36 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> -            FileGroup fileGroup = meterDataSet.FileGroup;
It got moved up into line 275

2025-01-10 14:46 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    else if (status == FileGroupProcessingStatus.Failed) status = FileGroupProcessingStatus.PartialSuccess;
With the current code, on failure it should either
Be in `Failure` or `Partial Success`, in either case things shouldn't change.
Be in `Success` and go to `Partial Success`, as is the case on line 323. 

In the case you highlighted, the code I believe is doing the following.
Go from `Failure` to `Success` in `index = 0` (line 315)
Not change in `index = 1` (line  315-316, neither condition should be met)
Go from `Success` to `Partial Success` in `index = 2` (line 323)

2025-01-15 15:30 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    if (IsDisposed)
It will still exit the function completely, but only after logging the exception in the data operation failure. When we catch the exception on line 319, there is a block that checks `IsDisposed `on line 334. If we are, we return out of the function, and never move onto another definition.

2025-01-15 15:30 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
> +                    if (IsDisposed)
This makes sense, updated.

2025-01-15 15:34 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Nodes/Types/Analysis/AnalysisNode.cs
>          }
This is a good suggestion, thank you.

2025-01-24 10:30 UTC, clackner-gpa approved these changes

2025-01-24 10:30 UTC, clackner-gpa commented on Source/Libraries/openXDA.Model/System/DataOperationFailure.cs
> +    [AllowSearch]
```suggestion
    [PostRoles("")]
    [PatchRoles("")]
    [DeleteRoles("Administrator, Transmission SME")]
    [AllowSearch]
```
Nitpicky, but I don't think these should be editable via a controller. Only written by the system

2025-01-24 11:34 UTC, gcsantos-gpa commented on Source/Libraries/openXDA.Model/System/DataOperationFailure.cs
> +    [AllowSearch]
Good catch!

2025-01-24 12:21 UTC, clackner-gpa approved these changes

2025-01-24 12:21 UTC, merged